version: '3'

services:
  cache:
    image: redis/redis-stack
    hostname: cache
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
