// Code generated by templ@v0.2.364 DO NOT EDIT.

package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Modal() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div id=\"modal\"><div id=\"modal-underlay\" class=\"modal-underlay\"></div><div class=\"modal-content text-sm font-mono\"><h6 class=\"font-bold mb-3\">")
		if err != nil {
			return err
		}
		var_2 := `Join lobby.`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><p class=\"lowercase\">")
		if err != nil {
			return err
		}
		var_3 := `Joining a friend? enter the lobby ID to join their game`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><form action=\"\" id=\"join-lobby-form\" class=\"mt-5\"><div id=\"lobby-id-form-group\"><label id=\"lobby-id-label\" for=\"lobby-id\"></label><input autocomplete=\"off\" id=\"lobby-id\" pattern=\"[A-Z0-9]{4}\" class=\"bg-gray-200 rounded-md border-2 border-gray-300 px-3 py-2\" type=\"text\"></div><div class=\"flex gap-x-5 mt-5\"><button type=\"submit\" id=\"join-lobby-btn\" class=\"px-2 py-1.5 border-2 border-transparent hover:border-blue-700 rounded-md\">")
		if err != nil {
			return err
		}
		var_4 := `join lobby`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><button type=\"button\" id=\"modal-btn\" class=\"px-2 py-1.5 border-2 border-transparent hover:border-red-500 rounded-md\">")
		if err != nil {
			return err
		}
		var_5 := `close modal`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></div></form></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
