// Code generated by templ@v0.2.364 DO NOT EDIT.

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func CreateLobbyPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<main id=\"main_container\" class=\"bg-blue-700 min-h-screen px-12 pt-12 pb-24\"><div class=\"h-[25vh] p-12 font-mono bg-white rounded-md\"><h1 class=\"text-2xl font-black\">")
		if err != nil {
			return err
		}
		var_2 := `Create a new lobby`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><form hx-trigger=\"submit\" id=\"create-lobby-form\" class=\"flex gap-3 items-end mt-12\"><div class=\"flex flex-col\"><label for=\"num_of_players\" class=\"font-black\">")
		if err != nil {
			return err
		}
		var_3 := `number of players`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"number\" class=\"bg-gray-200 px-2 py-1.5 rounded-md\" name=\"num_of_players\" id=\"num_of_players\"></div><div class=\"flex flex-col\"><label for=\"max_hand_size\" class=\"font-black\">")
		if err != nil {
			return err
		}
		var_4 := `max hand size`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"number\" class=\"bg-gray-200 px-2 py-1.5 rounded-md\" name=\"max_hand_size\" id=\"max_hand_size\"></div><button class=\"px-2 py-1 border-2 border-transparent rounded-md hover:border-blue-700 bg-gray-200\">")
		if err != nil {
			return err
		}
		var_5 := `create lobby`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></form></div><script src=\"/bundle/js/create_lobby.js\">")
		if err != nil {
			return err
		}
		var_6 := ``
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</script></main>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
