// Code generated by templ@v0.2.364 DO NOT EDIT.

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func IndexPage(username string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<main id=\"main_container\" class=\"bg-blue-700 min-h-screen px-12 pt-12 pb-24\"><div class=\"bg-white h-[90vh] rounded-lg p-12\"><div class=\"flex h-full flex-col justify-center items-center p-4 gap-y-2 font-mono\"><div class=\"border-4 border-blue-700  p-5 rounded-md \"><h1 class=\"font-mono text-5xl text-black font-black lowercase my-2\">")
		if err != nil {
			return err
		}
		var_2 := `go-Sequence`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><!--")
		if err != nil {
			return err
		}
		var_3 := ` Username generation`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"flex flex-col justify-center items-center\">")
		if err != nil {
			return err
		}
		if username == "" {
			_, err = templBuffer.WriteString("<button class=\"bg-blue-700 px-1.5 py-1 rounded-md text-white transform border-transparent border-2 hover:bg-white hover:border-blue-700 hover:text-black duration-150 ease-out\" id=\"generate-btn\" hx-get=\"/lobby/generate_username\" hx-target=\"#generated_username\">")
			if err != nil {
				return err
			}
			var_4 := `generate username`
			_, err = templBuffer.WriteString(var_4)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button> <h4 id=\"generated_username\" class=\"my-1 cursor-copy hover:bg-gray-100 px-1 py-0.5\"></h4>")
			if err != nil {
				return err
			}
		} else {
			_, err = templBuffer.WriteString("<h4 id=\"generated_username\" class=\"my-1 cursor-copy hover:bg-gray-100 px-1 py-0.5\">")
			if err != nil {
				return err
			}
			var var_5 string = username
			_, err = templBuffer.WriteString(templ.EscapeString(var_5))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</h4>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</div><div class=\"flex gap-5\">")
		if err != nil {
			return err
		}
		if username == "" {
			_, err = templBuffer.WriteString("<a hx-get=\"/lobby/view/toast/prompt-username\" hx-target=\"body\" hx-swap=\"beforeend\" class=\"bg-white px-3 py-2 rounded-xl hover:bg-blue-700 hover:text-white transition duration-200 hover:rounded-md ease-linear\">")
			if err != nil {
				return err
			}
			var_6 := `Create lobby`
			_, err = templBuffer.WriteString(var_6)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a> <button hx-get=\"/lobby/view/toast/prompt-username\" hx-target=\"body\" hx-swap=\"beforeend\" class=\"bg-white px-3 py-2 rounded-xl hover:bg-blue-700 hover:text-white transition duration-200 hover:rounded-md ease-linear\">")
			if err != nil {
				return err
			}
			var_7 := `Join lobby`
			_, err = templBuffer.WriteString(var_7)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button>")
			if err != nil {
				return err
			}
		} else {
			_, err = templBuffer.WriteString("<a href=\"/lobby-create\" class=\"bg-white px-3 py-2 rounded-xl hover:bg-blue-700 hover:text-white transition duration-200 hover:rounded-md ease-linear\">")
			if err != nil {
				return err
			}
			var_8 := `Create lobby`
			_, err = templBuffer.WriteString(var_8)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a> <button hx-get=\"/lobby/view/modal/join-lobby\" hx-target=\"body\" hx-swap=\"beforeend\" class=\"bg-white px-3 py-2 rounded-xl hover:bg-blue-700 hover:text-white transition duration-200 hover:rounded-md ease-linear\">")
			if err != nil {
				return err
			}
			var_9 := `Join lobby`
			_, err = templBuffer.WriteString(var_9)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</div></div></div></div><script src=\"/bundle/js/index.js\">")
		if err != nil {
			return err
		}
		var_10 := ``
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</script></main>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
