// Code generated by templ@v0.2.364 DO NOT EDIT.

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func LobbyPage(connectionString, lobbyId, username string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<main id=\"main_container\" class=\"bg-blue-700 min-h-screen px-12 pt-12 pb-24 font-mono\" hx-ext=\"ws\" hx-swap-oob=\"beforeend\" ws-connect=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(connectionString))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><div id=\"username\" data-username=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(username))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"></div><div id=\"lobby-id\" data-lobby-id=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(lobbyId))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"></div><div class=\"grid grid-rows-lobby_grid grid-cols-5 gap-3 h-[75vh] rounded-md\"><!--")
		if err != nil {
			return err
		}
		var_2 := ` Header row  `
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"col-span-full row-span-1 bg-white flex items-center rounded-md p-5\"><h1 class=\"text-2xl\">")
		if err != nil {
			return err
		}
		var_3 := `Lobby id: `
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		var var_4 string = lobbyId
		_, err = templBuffer.WriteString(templ.EscapeString(var_4))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1></div><!--")
		if err != nil {
			return err
		}
		var_5 := ` Player settings `
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"row-start-2 row-end-3 col-span-3 bg-white rounded-md\"></div><!--")
		if err != nil {
			return err
		}
		var_6 := ` Player chat`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"row-start-2 row-end-3 col-span-2 bg-white rounded-md p-3 flex flex-col \"><!--")
		if err != nil {
			return err
		}
		var_7 := ` Chat messages  `
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"bg-gray-100 h-full rounded-t-md border-2 border-b-transparent\"><div id=\"ws-events\"></div></div><!--")
		if err != nil {
			return err
		}
		var_8 := ` Chat input  `
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--><div class=\"rounded-b-md border-2 border-t-transparent flex flex-grow\"><textarea ws-send hx-trigger=\"keydown[!shiftKey&amp;&amp;key==&#39;Enter&#39;]\" form=\"chat-form\" rows=\"3\" cols=\"33\" class=\"bg-gray-200 px-1.5 py-0.5 rounded-md resize-none\" id=\"chat-input\" name=\"message\" type=\"text\"></textarea></div></div></div><script src=\"/bundle/js/lobby.js\">")
		if err != nil {
			return err
		}
		var_9 := ``
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</script></main>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
